---
title: Vertcoin Block Reward Halving
email: latitudemt8848@gmail.com
description: A static website for halving countdown
url: http://pupreti.github.io
markdown: kramdown
exclude:
  - bin
  - vendor
